services:
  - type: web
    name: spark2scale-ai
    runtime: python
    plan: free
    branch: deployment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
